### ISSUE TITLE
Some cases install fails for permission issues, here is one workaround 

### ISSUE THREAD

**Issue by ddffx** [cloud-compose/cloud-compose-cluster#31]
I got an error like this when tried to install *cloud-compose-cluster*. Used -U flag to check the error
```
> pip install  -U cloud-compose-cluster

...

copying build/lib.macosx-10.12-intel-2.7/markupsafe/_speedups.so -> /Library/Python/2.7/site-packages/markupsafe
error: could not delete '/Library/Python/2.7/site-packages/markupsafe/_speedups.so': Permission denied
```
I was able to install in using `--user` flag

```
pip install -U --user cloud-compose-cluster
```

Hope this helps!

**Comment by patrickbcullen** [comment]
This is expected pip behavior as far as I know. You can put sudo in front of the pip command to install to the system python or use a virtualenv if you don't want to do that.
